root = "."
tmp_dir = "bin/air"

[build]
  cmd = "go build -o bin/air/flockdeck ./cmd/server"
  bin = "bin/air/flockdeck"
  include_ext = ["go"]
  exclude_dir = ["bin", "migrations"]
  delay = 500

[log]
  time = false
