// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM cards
WHERE user_id = $1 AND species_code = $2 AND lane = $3
`

type DeleteCardParams struct {
	UserID      int64  `db:"user_id" json:"user_id"`
	SpeciesCode string `db:"species_code" json:"species_code"`
	Lane        string `db:"lane" json:"lane"`
}

func (q *Queries) DeleteCard(ctx context.Context, arg DeleteCardParams) error {
	_, err := q.db.Exec(ctx, deleteCard, arg.UserID, arg.SpeciesCode, arg.Lane)
	return err
}

const getCard = `-- name: GetCard :one
SELECT id, user_id, species_code, lane, stability, difficulty, due,
       last_review, reps, lapses, state, created_at
FROM cards
WHERE user_id = $1 AND species_code = $2 AND lane = $3
`

type GetCardParams struct {
	UserID      int64  `db:"user_id" json:"user_id"`
	SpeciesCode string `db:"species_code" json:"species_code"`
	Lane        string `db:"lane" json:"lane"`
}

func (q *Queries) GetCard(ctx context.Context, arg GetCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, getCard, arg.UserID, arg.SpeciesCode, arg.Lane)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SpeciesCode,
		&i.Lane,
		&i.Stability,
		&i.Difficulty,
		&i.Due,
		&i.LastReview,
		&i.Reps,
		&i.Lapses,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupPracticeCards = `-- name: GetGroupPracticeCards :many
SELECT s.ebird_code, s.common_name, s.scientific_name,
       COALESCE(
           (SELECT file_path FROM species_recordings
            WHERE species_code = s.ebird_code AND quality IN ('A', 'B')
            ORDER BY random() LIMIT 1),
           ''
       )::text AS audio_url,
       COALESCE(
           (SELECT file_path FROM species_images
            WHERE species_code = s.ebird_code
            ORDER BY random() LIMIT 1),
           ''
       )::text AS image_url
FROM species s
JOIN group_species gs ON gs.species_code = s.ebird_code
WHERE gs.group_id = $1
ORDER BY s.common_name
`

type GetGroupPracticeCardsRow struct {
	EbirdCode      string `db:"ebird_code" json:"ebird_code"`
	CommonName     string `db:"common_name" json:"common_name"`
	ScientificName string `db:"scientific_name" json:"scientific_name"`
	AudioUrl       string `db:"audio_url" json:"audio_url"`
	ImageUrl       string `db:"image_url" json:"image_url"`
}

func (q *Queries) GetGroupPracticeCards(ctx context.Context, groupID int64) ([]GetGroupPracticeCardsRow, error) {
	rows, err := q.db.Query(ctx, getGroupPracticeCards, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupPracticeCardsRow
	for rows.Next() {
		var i GetGroupPracticeCardsRow
		if err := rows.Scan(
			&i.EbirdCode,
			&i.CommonName,
			&i.ScientificName,
			&i.AudioUrl,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextDueCard = `-- name: GetNextDueCard :one
SELECT c.id, c.user_id, c.species_code, c.lane,
       c.stability, c.difficulty, c.due, c.last_review,
       c.reps, c.lapses, c.state, c.created_at,
       s.common_name, s.scientific_name
FROM cards c
JOIN species s ON s.ebird_code = c.species_code
JOIN group_species gs ON gs.species_code = c.species_code
WHERE c.user_id = $1
  AND gs.group_id = $2
  AND c.lane = $3
  AND c.due <= NOW()
ORDER BY c.due
LIMIT 1
`

type GetNextDueCardParams struct {
	UserID  int64  `db:"user_id" json:"user_id"`
	GroupID int64  `db:"group_id" json:"group_id"`
	Lane    string `db:"lane" json:"lane"`
}

type GetNextDueCardRow struct {
	ID             int64              `db:"id" json:"id"`
	UserID         int64              `db:"user_id" json:"user_id"`
	SpeciesCode    string             `db:"species_code" json:"species_code"`
	Lane           string             `db:"lane" json:"lane"`
	Stability      float64            `db:"stability" json:"stability"`
	Difficulty     float64            `db:"difficulty" json:"difficulty"`
	Due            pgtype.Timestamptz `db:"due" json:"due"`
	LastReview     pgtype.Timestamptz `db:"last_review" json:"last_review"`
	Reps           int32              `db:"reps" json:"reps"`
	Lapses         int32              `db:"lapses" json:"lapses"`
	State          int16              `db:"state" json:"state"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CommonName     string             `db:"common_name" json:"common_name"`
	ScientificName string             `db:"scientific_name" json:"scientific_name"`
}

func (q *Queries) GetNextDueCard(ctx context.Context, arg GetNextDueCardParams) (GetNextDueCardRow, error) {
	row := q.db.QueryRow(ctx, getNextDueCard, arg.UserID, arg.GroupID, arg.Lane)
	var i GetNextDueCardRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SpeciesCode,
		&i.Lane,
		&i.Stability,
		&i.Difficulty,
		&i.Due,
		&i.LastReview,
		&i.Reps,
		&i.Lapses,
		&i.State,
		&i.CreatedAt,
		&i.CommonName,
		&i.ScientificName,
	)
	return i, err
}

const getRandomImage = `-- name: GetRandomImage :one
SELECT file_path FROM species_images
WHERE species_code = $1
ORDER BY random()
LIMIT 1
`

func (q *Queries) GetRandomImage(ctx context.Context, speciesCode string) (string, error) {
	row := q.db.QueryRow(ctx, getRandomImage, speciesCode)
	var file_path string
	err := row.Scan(&file_path)
	return file_path, err
}

const getRandomRecording = `-- name: GetRandomRecording :one
SELECT file_path FROM species_recordings
WHERE species_code = $1 AND quality IN ('A', 'B')
ORDER BY random()
LIMIT 1
`

func (q *Queries) GetRandomRecording(ctx context.Context, speciesCode string) (string, error) {
	row := q.db.QueryRow(ctx, getRandomRecording, speciesCode)
	var file_path string
	err := row.Scan(&file_path)
	return file_path, err
}

const updateCardSchedule = `-- name: UpdateCardSchedule :one
UPDATE cards
SET stability   = $4,
    difficulty  = $5,
    due         = $6,
    last_review = NOW(),
    reps        = reps + 1,
    lapses      = $7,
    state       = $8
WHERE user_id = $1 AND species_code = $2 AND lane = $3
RETURNING id, user_id, species_code, lane, stability, difficulty, due,
          last_review, reps, lapses, state, created_at
`

type UpdateCardScheduleParams struct {
	UserID      int64              `db:"user_id" json:"user_id"`
	SpeciesCode string             `db:"species_code" json:"species_code"`
	Lane        string             `db:"lane" json:"lane"`
	Stability   float64            `db:"stability" json:"stability"`
	Difficulty  float64            `db:"difficulty" json:"difficulty"`
	Due         pgtype.Timestamptz `db:"due" json:"due"`
	Lapses      int32              `db:"lapses" json:"lapses"`
	State       int16              `db:"state" json:"state"`
}

func (q *Queries) UpdateCardSchedule(ctx context.Context, arg UpdateCardScheduleParams) (Card, error) {
	row := q.db.QueryRow(ctx, updateCardSchedule,
		arg.UserID,
		arg.SpeciesCode,
		arg.Lane,
		arg.Stability,
		arg.Difficulty,
		arg.Due,
		arg.Lapses,
		arg.State,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SpeciesCode,
		&i.Lane,
		&i.Stability,
		&i.Difficulty,
		&i.Due,
		&i.LastReview,
		&i.Reps,
		&i.Lapses,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCard = `-- name: UpsertCard :exec
INSERT INTO cards (user_id, species_code, lane)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, species_code, lane) DO NOTHING
`

type UpsertCardParams struct {
	UserID      int64  `db:"user_id" json:"user_id"`
	SpeciesCode string `db:"species_code" json:"species_code"`
	Lane        string `db:"lane" json:"lane"`
}

func (q *Queries) UpsertCard(ctx context.Context, arg UpsertCardParams) error {
	_, err := q.db.Exec(ctx, upsertCard, arg.UserID, arg.SpeciesCode, arg.Lane)
	return err
}
