// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDueCards = `-- name: CountDueCards :one
SELECT COUNT(*)
FROM cards c
JOIN deck_species ds ON ds.species_code = c.species_code
WHERE c.user_id = $1
  AND ds.deck_id = $2
  AND c.lane = $3
  AND c.due <= NOW()
`

type CountDueCardsParams struct {
	UserID int64  `db:"user_id" json:"user_id"`
	DeckID int64  `db:"deck_id" json:"deck_id"`
	Lane   string `db:"lane" json:"lane"`
}

func (q *Queries) CountDueCards(ctx context.Context, arg CountDueCardsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDueCards, arg.UserID, arg.DeckID, arg.Lane)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM cards
WHERE user_id = $1 AND species_code = $2 AND lane = $3
`

type DeleteCardParams struct {
	UserID      int64  `db:"user_id" json:"user_id"`
	SpeciesCode string `db:"species_code" json:"species_code"`
	Lane        string `db:"lane" json:"lane"`
}

func (q *Queries) DeleteCard(ctx context.Context, arg DeleteCardParams) error {
	_, err := q.db.Exec(ctx, deleteCard, arg.UserID, arg.SpeciesCode, arg.Lane)
	return err
}

const getCard = `-- name: GetCard :one
SELECT id, user_id, species_code, lane, stability, difficulty, due,
       last_review, reps, lapses, state, created_at
FROM cards
WHERE user_id = $1 AND species_code = $2 AND lane = $3
`

type GetCardParams struct {
	UserID      int64  `db:"user_id" json:"user_id"`
	SpeciesCode string `db:"species_code" json:"species_code"`
	Lane        string `db:"lane" json:"lane"`
}

func (q *Queries) GetCard(ctx context.Context, arg GetCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, getCard, arg.UserID, arg.SpeciesCode, arg.Lane)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SpeciesCode,
		&i.Lane,
		&i.Stability,
		&i.Difficulty,
		&i.Due,
		&i.LastReview,
		&i.Reps,
		&i.Lapses,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const getDeckPracticeCards = `-- name: GetDeckPracticeCards :many
SELECT s.ebird_code, s.common_name, s.scientific_name,
       COALESCE(rec.file_path, '') AS audio_url,
       COALESCE(rec.credit, '')    AS audio_credit,
       COALESCE(img.file_path, '') AS image_url,
       COALESCE(img.credit, '')    AS image_credit
FROM species s
JOIN deck_species ds ON ds.species_code = s.ebird_code
LEFT JOIN LATERAL (
    SELECT file_path, credit FROM species_recordings
    WHERE species_code = s.ebird_code AND quality IN ('A', 'B')
    ORDER BY random() LIMIT 1
) rec ON true
LEFT JOIN LATERAL (
    SELECT file_path, credit FROM species_images
    WHERE species_code = s.ebird_code
    ORDER BY random() LIMIT 1
) img ON true
WHERE ds.deck_id = $1
ORDER BY s.common_name
`

type GetDeckPracticeCardsRow struct {
	EbirdCode      string `db:"ebird_code" json:"ebird_code"`
	CommonName     string `db:"common_name" json:"common_name"`
	ScientificName string `db:"scientific_name" json:"scientific_name"`
	AudioUrl       string `db:"audio_url" json:"audio_url"`
	AudioCredit    string `db:"audio_credit" json:"audio_credit"`
	ImageUrl       string `db:"image_url" json:"image_url"`
	ImageCredit    string `db:"image_credit" json:"image_credit"`
}

func (q *Queries) GetDeckPracticeCards(ctx context.Context, deckID int64) ([]GetDeckPracticeCardsRow, error) {
	rows, err := q.db.Query(ctx, getDeckPracticeCards, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeckPracticeCardsRow
	for rows.Next() {
		var i GetDeckPracticeCardsRow
		if err := rows.Scan(
			&i.EbirdCode,
			&i.CommonName,
			&i.ScientificName,
			&i.AudioUrl,
			&i.AudioCredit,
			&i.ImageUrl,
			&i.ImageCredit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextDueAt = `-- name: GetNextDueAt :one
SELECT due AS next_due_at
FROM cards
WHERE user_id = $1
  AND due > NOW()
ORDER BY due
LIMIT 1
`

func (q *Queries) GetNextDueAt(ctx context.Context, userID int64) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getNextDueAt, userID)
	var next_due_at pgtype.Timestamptz
	err := row.Scan(&next_due_at)
	return next_due_at, err
}

const getNextDueCard = `-- name: GetNextDueCard :one
SELECT c.id, c.user_id, c.species_code, c.lane,
       c.stability, c.difficulty, c.due, c.last_review,
       c.reps, c.lapses, c.state, c.created_at,
       s.common_name, s.scientific_name
FROM cards c
JOIN species s ON s.ebird_code = c.species_code
JOIN deck_species ds ON ds.species_code = c.species_code
WHERE c.user_id = $1
  AND ds.deck_id = $2
  AND c.lane = $3
  AND c.due <= NOW()
ORDER BY c.due
LIMIT 1
`

type GetNextDueCardParams struct {
	UserID int64  `db:"user_id" json:"user_id"`
	DeckID int64  `db:"deck_id" json:"deck_id"`
	Lane   string `db:"lane" json:"lane"`
}

type GetNextDueCardRow struct {
	ID             int64              `db:"id" json:"id"`
	UserID         int64              `db:"user_id" json:"user_id"`
	SpeciesCode    string             `db:"species_code" json:"species_code"`
	Lane           string             `db:"lane" json:"lane"`
	Stability      float64            `db:"stability" json:"stability"`
	Difficulty     float64            `db:"difficulty" json:"difficulty"`
	Due            pgtype.Timestamptz `db:"due" json:"due"`
	LastReview     pgtype.Timestamptz `db:"last_review" json:"last_review"`
	Reps           int32              `db:"reps" json:"reps"`
	Lapses         int32              `db:"lapses" json:"lapses"`
	State          int16              `db:"state" json:"state"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CommonName     string             `db:"common_name" json:"common_name"`
	ScientificName string             `db:"scientific_name" json:"scientific_name"`
}

func (q *Queries) GetNextDueCard(ctx context.Context, arg GetNextDueCardParams) (GetNextDueCardRow, error) {
	row := q.db.QueryRow(ctx, getNextDueCard, arg.UserID, arg.DeckID, arg.Lane)
	var i GetNextDueCardRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SpeciesCode,
		&i.Lane,
		&i.Stability,
		&i.Difficulty,
		&i.Due,
		&i.LastReview,
		&i.Reps,
		&i.Lapses,
		&i.State,
		&i.CreatedAt,
		&i.CommonName,
		&i.ScientificName,
	)
	return i, err
}

const getRandomImage = `-- name: GetRandomImage :one
SELECT file_path, credit FROM species_images
WHERE species_code = $1
ORDER BY random()
LIMIT 1
`

type GetRandomImageRow struct {
	FilePath string `db:"file_path" json:"file_path"`
	Credit   string `db:"credit" json:"credit"`
}

func (q *Queries) GetRandomImage(ctx context.Context, speciesCode string) (GetRandomImageRow, error) {
	row := q.db.QueryRow(ctx, getRandomImage, speciesCode)
	var i GetRandomImageRow
	err := row.Scan(&i.FilePath, &i.Credit)
	return i, err
}

const getRandomRecording = `-- name: GetRandomRecording :one
SELECT file_path, type, credit FROM species_recordings
WHERE species_code = $1 AND quality IN ('A', 'B')
ORDER BY random()
LIMIT 1
`

type GetRandomRecordingRow struct {
	FilePath string `db:"file_path" json:"file_path"`
	Type     string `db:"type" json:"type"`
	Credit   string `db:"credit" json:"credit"`
}

func (q *Queries) GetRandomRecording(ctx context.Context, speciesCode string) (GetRandomRecordingRow, error) {
	row := q.db.QueryRow(ctx, getRandomRecording, speciesCode)
	var i GetRandomRecordingRow
	err := row.Scan(&i.FilePath, &i.Type, &i.Credit)
	return i, err
}

const updateCardSchedule = `-- name: UpdateCardSchedule :one
UPDATE cards
SET stability   = $4,
    difficulty  = $5,
    due         = $6,
    last_review = NOW(),
    reps        = reps + 1,
    lapses      = $7,
    state       = $8
WHERE user_id = $1 AND species_code = $2 AND lane = $3
RETURNING id, user_id, species_code, lane, stability, difficulty, due,
          last_review, reps, lapses, state, created_at
`

type UpdateCardScheduleParams struct {
	UserID      int64              `db:"user_id" json:"user_id"`
	SpeciesCode string             `db:"species_code" json:"species_code"`
	Lane        string             `db:"lane" json:"lane"`
	Stability   float64            `db:"stability" json:"stability"`
	Difficulty  float64            `db:"difficulty" json:"difficulty"`
	Due         pgtype.Timestamptz `db:"due" json:"due"`
	Lapses      int32              `db:"lapses" json:"lapses"`
	State       int16              `db:"state" json:"state"`
}

func (q *Queries) UpdateCardSchedule(ctx context.Context, arg UpdateCardScheduleParams) (Card, error) {
	row := q.db.QueryRow(ctx, updateCardSchedule,
		arg.UserID,
		arg.SpeciesCode,
		arg.Lane,
		arg.Stability,
		arg.Difficulty,
		arg.Due,
		arg.Lapses,
		arg.State,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SpeciesCode,
		&i.Lane,
		&i.Stability,
		&i.Difficulty,
		&i.Due,
		&i.LastReview,
		&i.Reps,
		&i.Lapses,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCard = `-- name: UpsertCard :exec
INSERT INTO cards (user_id, species_code, lane)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, species_code, lane) DO NOTHING
`

type UpsertCardParams struct {
	UserID      int64  `db:"user_id" json:"user_id"`
	SpeciesCode string `db:"species_code" json:"species_code"`
	Lane        string `db:"lane" json:"lane"`
}

func (q *Queries) UpsertCard(ctx context.Context, arg UpsertCardParams) error {
	_, err := q.db.Exec(ctx, upsertCard, arg.UserID, arg.SpeciesCode, arg.Lane)
	return err
}

const upsertCardsForDeck = `-- name: UpsertCardsForDeck :exec
INSERT INTO cards (user_id, species_code, lane)
SELECT $1, ds.species_code, l.lane
FROM deck_species ds
CROSS JOIN (VALUES ('audio'::text), ('image'::text)) AS l(lane)
WHERE ds.deck_id = $2
ON CONFLICT (user_id, species_code, lane) DO NOTHING
`

type UpsertCardsForDeckParams struct {
	UserID int64 `db:"user_id" json:"user_id"`
	DeckID int64 `db:"deck_id" json:"deck_id"`
}

func (q *Queries) UpsertCardsForDeck(ctx context.Context, arg UpsertCardsForDeckParams) error {
	_, err := q.db.Exec(ctx, upsertCardsForDeck, arg.UserID, arg.DeckID)
	return err
}
