// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDueCards = `-- name: GetDueCards :many
SELECT c.id, c.user_id, c.recording_id, c.stability, c.difficulty, c.due, c.last_review, c.reps, c.lapses, c.state, c.created_at, r.file_path AS recording_path, s.common_name, s.scientific_name
FROM cards c
JOIN recordings r ON r.id = c.recording_id
JOIN species s ON s.id = r.species_id
WHERE c.user_id = $1 AND c.due <= NOW()
ORDER BY c.due
LIMIT $2
`

type GetDueCardsParams struct {
	UserID int64 `db:"user_id" json:"user_id"`
	Limit  int32 `db:"limit" json:"limit"`
}

type GetDueCardsRow struct {
	ID             int64              `db:"id" json:"id"`
	UserID         int64              `db:"user_id" json:"user_id"`
	RecordingID    int64              `db:"recording_id" json:"recording_id"`
	Stability      float64            `db:"stability" json:"stability"`
	Difficulty     float64            `db:"difficulty" json:"difficulty"`
	Due            pgtype.Timestamptz `db:"due" json:"due"`
	LastReview     pgtype.Timestamptz `db:"last_review" json:"last_review"`
	Reps           int32              `db:"reps" json:"reps"`
	Lapses         int32              `db:"lapses" json:"lapses"`
	State          int16              `db:"state" json:"state"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	RecordingPath  string             `db:"recording_path" json:"recording_path"`
	CommonName     string             `db:"common_name" json:"common_name"`
	ScientificName string             `db:"scientific_name" json:"scientific_name"`
}

func (q *Queries) GetDueCards(ctx context.Context, arg GetDueCardsParams) ([]GetDueCardsRow, error) {
	rows, err := q.db.Query(ctx, getDueCards, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDueCardsRow
	for rows.Next() {
		var i GetDueCardsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RecordingID,
			&i.Stability,
			&i.Difficulty,
			&i.Due,
			&i.LastReview,
			&i.Reps,
			&i.Lapses,
			&i.State,
			&i.CreatedAt,
			&i.RecordingPath,
			&i.CommonName,
			&i.ScientificName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCardSchedule = `-- name: UpdateCardSchedule :one
UPDATE cards
SET stability   = $3,
    difficulty  = $4,
    due         = $5,
    last_review = NOW(),
    reps        = reps + 1,
    lapses      = $6,
    state       = $7
WHERE user_id = $1 AND recording_id = $2
RETURNING id, user_id, recording_id, stability, difficulty, due, last_review, reps, lapses, state, created_at
`

type UpdateCardScheduleParams struct {
	UserID      int64              `db:"user_id" json:"user_id"`
	RecordingID int64              `db:"recording_id" json:"recording_id"`
	Stability   float64            `db:"stability" json:"stability"`
	Difficulty  float64            `db:"difficulty" json:"difficulty"`
	Due         pgtype.Timestamptz `db:"due" json:"due"`
	Lapses      int32              `db:"lapses" json:"lapses"`
	State       int16              `db:"state" json:"state"`
}

func (q *Queries) UpdateCardSchedule(ctx context.Context, arg UpdateCardScheduleParams) (Card, error) {
	row := q.db.QueryRow(ctx, updateCardSchedule,
		arg.UserID,
		arg.RecordingID,
		arg.Stability,
		arg.Difficulty,
		arg.Due,
		arg.Lapses,
		arg.State,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecordingID,
		&i.Stability,
		&i.Difficulty,
		&i.Due,
		&i.LastReview,
		&i.Reps,
		&i.Lapses,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCard = `-- name: UpsertCard :one
INSERT INTO cards (user_id, recording_id)
VALUES ($1, $2)
ON CONFLICT (user_id, recording_id) DO NOTHING
RETURNING id, user_id, recording_id, stability, difficulty, due, last_review, reps, lapses, state, created_at
`

type UpsertCardParams struct {
	UserID      int64 `db:"user_id" json:"user_id"`
	RecordingID int64 `db:"recording_id" json:"recording_id"`
}

func (q *Queries) UpsertCard(ctx context.Context, arg UpsertCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, upsertCard, arg.UserID, arg.RecordingID)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecordingID,
		&i.Stability,
		&i.Difficulty,
		&i.Due,
		&i.LastReview,
		&i.Reps,
		&i.Lapses,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}
