// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decks.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addSpeciesToDeck = `-- name: AddSpeciesToDeck :exec
INSERT INTO deck_species (deck_id, species_code)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddSpeciesToDeckParams struct {
	DeckID      int64  `db:"deck_id" json:"deck_id"`
	SpeciesCode string `db:"species_code" json:"species_code"`
}

func (q *Queries) AddSpeciesToDeck(ctx context.Context, arg AddSpeciesToDeckParams) error {
	_, err := q.db.Exec(ctx, addSpeciesToDeck, arg.DeckID, arg.SpeciesCode)
	return err
}

const bulkAddSpeciesToDeck = `-- name: BulkAddSpeciesToDeck :execrows
INSERT INTO deck_species (deck_id, species_code)
SELECT $1, code FROM unnest($2::text[]) AS code
ON CONFLICT DO NOTHING
`

type BulkAddSpeciesToDeckParams struct {
	DeckID  int64    `db:"deck_id" json:"deck_id"`
	Column2 []string `db:"column_2" json:"column_2"`
}

func (q *Queries) BulkAddSpeciesToDeck(ctx context.Context, arg BulkAddSpeciesToDeckParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkAddSpeciesToDeck, arg.DeckID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cloneDeckSpecies = `-- name: CloneDeckSpecies :exec
INSERT INTO deck_species (deck_id, species_code)
SELECT $2, src.species_code FROM deck_species src WHERE src.deck_id = $1
ON CONFLICT DO NOTHING
`

type CloneDeckSpeciesParams struct {
	DeckID   int64 `db:"deck_id" json:"deck_id"`
	DeckID_2 int64 `db:"deck_id_2" json:"deck_id_2"`
}

func (q *Queries) CloneDeckSpecies(ctx context.Context, arg CloneDeckSpeciesParams) error {
	_, err := q.db.Exec(ctx, cloneDeckSpecies, arg.DeckID, arg.DeckID_2)
	return err
}

const createDeck = `-- name: CreateDeck :one
INSERT INTO decks (name, description, owner_id)
VALUES ($1, $2, $3)
RETURNING id, name, description, owner_id, created_at
`

type CreateDeckParams struct {
	Name        string      `db:"name" json:"name"`
	Description string      `db:"description" json:"description"`
	OwnerID     pgtype.Int8 `db:"owner_id" json:"owner_id"`
}

func (q *Queries) CreateDeck(ctx context.Context, arg CreateDeckParams) (Deck, error) {
	row := q.db.QueryRow(ctx, createDeck, arg.Name, arg.Description, arg.OwnerID)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const createPresetDeck = `-- name: CreatePresetDeck :one
INSERT INTO decks (name, description)
VALUES ($1, $2)
RETURNING id, name, description, owner_id, created_at
`

type CreatePresetDeckParams struct {
	Name        string `db:"name" json:"name"`
	Description string `db:"description" json:"description"`
}

func (q *Queries) CreatePresetDeck(ctx context.Context, arg CreatePresetDeckParams) (Deck, error) {
	row := q.db.QueryRow(ctx, createPresetDeck, arg.Name, arg.Description)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDeck = `-- name: DeleteDeck :exec
DELETE FROM decks WHERE id = $1
`

func (q *Queries) DeleteDeck(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDeck, id)
	return err
}

const getDeck = `-- name: GetDeck :one
SELECT id, name, description, owner_id, created_at
FROM decks
WHERE id = $1
`

func (q *Queries) GetDeck(ctx context.Context, id int64) (Deck, error) {
	row := q.db.QueryRow(ctx, getDeck, id)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const getDeckWithDue = `-- name: GetDeckWithDue :one
SELECT d.id, d.name, d.description, d.owner_id, d.created_at,
    COUNT(CASE WHEN c.lane = 'audio' AND c.due <= NOW() AND COALESCE(usp.audio_enabled, true) THEN 1 END) AS audio_due,
    COUNT(CASE WHEN c.lane = 'image' AND c.due <= NOW() AND COALESCE(usp.image_enabled, true) THEN 1 END) AS image_due
FROM decks d
LEFT JOIN deck_species ds ON ds.deck_id = d.id
LEFT JOIN cards c ON c.species_code = ds.species_code AND c.user_id = $2
LEFT JOIN user_species_preferences usp ON usp.species_code = ds.species_code AND usp.user_id = $2
WHERE d.id = $1
GROUP BY d.id
`

type GetDeckWithDueParams struct {
	ID     int64 `db:"id" json:"id"`
	UserID int64 `db:"user_id" json:"user_id"`
}

type GetDeckWithDueRow struct {
	ID          int64              `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description string             `db:"description" json:"description"`
	OwnerID     pgtype.Int8        `db:"owner_id" json:"owner_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	AudioDue    int64              `db:"audio_due" json:"audio_due"`
	ImageDue    int64              `db:"image_due" json:"image_due"`
}

func (q *Queries) GetDeckWithDue(ctx context.Context, arg GetDeckWithDueParams) (GetDeckWithDueRow, error) {
	row := q.db.QueryRow(ctx, getDeckWithDue, arg.ID, arg.UserID)
	var i GetDeckWithDueRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
		&i.AudioDue,
		&i.ImageDue,
	)
	return i, err
}

const getDeckWithOwner = `-- name: GetDeckWithOwner :one
SELECT d.id, d.name, d.description, d.owner_id,
    COALESCE(u.name, '') AS owner_name,
    COALESCE(u.email, '') AS owner_email
FROM decks d
LEFT JOIN users u ON u.id = d.owner_id
WHERE d.id = $1
`

type GetDeckWithOwnerRow struct {
	ID          int64       `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Description string      `db:"description" json:"description"`
	OwnerID     pgtype.Int8 `db:"owner_id" json:"owner_id"`
	OwnerName   string      `db:"owner_name" json:"owner_name"`
	OwnerEmail  string      `db:"owner_email" json:"owner_email"`
}

func (q *Queries) GetDeckWithOwner(ctx context.Context, id int64) (GetDeckWithOwnerRow, error) {
	row := q.db.QueryRow(ctx, getDeckWithOwner, id)
	var i GetDeckWithOwnerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.OwnerName,
		&i.OwnerEmail,
	)
	return i, err
}

const listAllUserDecks = `-- name: ListAllUserDecks :many
SELECT d.id, d.name, d.description, d.created_at,
    u.id AS owner_id, u.name AS owner_name, u.email AS owner_email,
    COUNT(ds.species_code) AS species_count
FROM decks d
JOIN users u ON u.id = d.owner_id
LEFT JOIN deck_species ds ON ds.deck_id = d.id
WHERE d.owner_id IS NOT NULL
GROUP BY d.id, u.id
ORDER BY u.email, d.name
`

type ListAllUserDecksRow struct {
	ID           int64              `db:"id" json:"id"`
	Name         string             `db:"name" json:"name"`
	Description  string             `db:"description" json:"description"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	OwnerID      int64              `db:"owner_id" json:"owner_id"`
	OwnerName    string             `db:"owner_name" json:"owner_name"`
	OwnerEmail   string             `db:"owner_email" json:"owner_email"`
	SpeciesCount int64              `db:"species_count" json:"species_count"`
}

func (q *Queries) ListAllUserDecks(ctx context.Context) ([]ListAllUserDecksRow, error) {
	rows, err := q.db.Query(ctx, listAllUserDecks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllUserDecksRow
	for rows.Next() {
		var i ListAllUserDecksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.OwnerID,
			&i.OwnerName,
			&i.OwnerEmail,
			&i.SpeciesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeckSpeciesSimple = `-- name: ListDeckSpeciesSimple :many
SELECT s.ebird_code, s.common_name, s.scientific_name
FROM species s
JOIN deck_species ds ON ds.species_code = s.ebird_code
WHERE ds.deck_id = $1
ORDER BY s.common_name
`

type ListDeckSpeciesSimpleRow struct {
	EbirdCode      string `db:"ebird_code" json:"ebird_code"`
	CommonName     string `db:"common_name" json:"common_name"`
	ScientificName string `db:"scientific_name" json:"scientific_name"`
}

func (q *Queries) ListDeckSpeciesSimple(ctx context.Context, deckID int64) ([]ListDeckSpeciesSimpleRow, error) {
	rows, err := q.db.Query(ctx, listDeckSpeciesSimple, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeckSpeciesSimpleRow
	for rows.Next() {
		var i ListDeckSpeciesSimpleRow
		if err := rows.Scan(&i.EbirdCode, &i.CommonName, &i.ScientificName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeckSpeciesWithPrefs = `-- name: ListDeckSpeciesWithPrefs :many
SELECT s.ebird_code, s.common_name, s.scientific_name,
       COALESCE(p.audio_enabled, true) AS audio_enabled,
       COALESCE(p.image_enabled, true) AS image_enabled
FROM species s
JOIN deck_species ds ON ds.species_code = s.ebird_code
LEFT JOIN user_species_preferences p
       ON p.species_code = s.ebird_code AND p.user_id = $2
WHERE ds.deck_id = $1
ORDER BY s.common_name
`

type ListDeckSpeciesWithPrefsParams struct {
	DeckID int64 `db:"deck_id" json:"deck_id"`
	UserID int64 `db:"user_id" json:"user_id"`
}

type ListDeckSpeciesWithPrefsRow struct {
	EbirdCode      string `db:"ebird_code" json:"ebird_code"`
	CommonName     string `db:"common_name" json:"common_name"`
	ScientificName string `db:"scientific_name" json:"scientific_name"`
	AudioEnabled   bool   `db:"audio_enabled" json:"audio_enabled"`
	ImageEnabled   bool   `db:"image_enabled" json:"image_enabled"`
}

func (q *Queries) ListDeckSpeciesWithPrefs(ctx context.Context, arg ListDeckSpeciesWithPrefsParams) ([]ListDeckSpeciesWithPrefsRow, error) {
	rows, err := q.db.Query(ctx, listDeckSpeciesWithPrefs, arg.DeckID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeckSpeciesWithPrefsRow
	for rows.Next() {
		var i ListDeckSpeciesWithPrefsRow
		if err := rows.Scan(
			&i.EbirdCode,
			&i.CommonName,
			&i.ScientificName,
			&i.AudioEnabled,
			&i.ImageEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresetDecks = `-- name: ListPresetDecks :many
SELECT d.id, d.name, d.description, d.created_at,
    COUNT(ds.species_code) AS species_count
FROM decks d
LEFT JOIN deck_species ds ON ds.deck_id = d.id
WHERE d.owner_id IS NULL
GROUP BY d.id
ORDER BY d.name
`

type ListPresetDecksRow struct {
	ID           int64              `db:"id" json:"id"`
	Name         string             `db:"name" json:"name"`
	Description  string             `db:"description" json:"description"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	SpeciesCount int64              `db:"species_count" json:"species_count"`
}

func (q *Queries) ListPresetDecks(ctx context.Context) ([]ListPresetDecksRow, error) {
	rows, err := q.db.Query(ctx, listPresetDecks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPresetDecksRow
	for rows.Next() {
		var i ListPresetDecksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.SpeciesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDecks = `-- name: ListUserDecks :many
SELECT d.id, d.name, d.description, d.owner_id, d.created_at,
    COUNT(CASE WHEN c.lane = 'audio' AND c.due <= NOW() AND COALESCE(usp.audio_enabled, true) THEN 1 END) AS audio_due,
    COUNT(CASE WHEN c.lane = 'image' AND c.due <= NOW() AND COALESCE(usp.image_enabled, true) THEN 1 END) AS image_due
FROM decks d
LEFT JOIN deck_species ds ON ds.deck_id = d.id
LEFT JOIN cards c ON c.species_code = ds.species_code AND c.user_id = $1
LEFT JOIN user_species_preferences usp ON usp.species_code = ds.species_code AND usp.user_id = $1
WHERE d.owner_id = $1
GROUP BY d.id
ORDER BY d.name
`

type ListUserDecksRow struct {
	ID          int64              `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description string             `db:"description" json:"description"`
	OwnerID     pgtype.Int8        `db:"owner_id" json:"owner_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	AudioDue    int64              `db:"audio_due" json:"audio_due"`
	ImageDue    int64              `db:"image_due" json:"image_due"`
}

func (q *Queries) ListUserDecks(ctx context.Context, userID int64) ([]ListUserDecksRow, error) {
	rows, err := q.db.Query(ctx, listUserDecks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserDecksRow
	for rows.Next() {
		var i ListUserDecksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.CreatedAt,
			&i.AudioDue,
			&i.ImageDue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSpeciesFromDeck = `-- name: RemoveSpeciesFromDeck :exec
DELETE FROM deck_species
WHERE deck_id = $1 AND species_code = $2
`

type RemoveSpeciesFromDeckParams struct {
	DeckID      int64  `db:"deck_id" json:"deck_id"`
	SpeciesCode string `db:"species_code" json:"species_code"`
}

func (q *Queries) RemoveSpeciesFromDeck(ctx context.Context, arg RemoveSpeciesFromDeckParams) error {
	_, err := q.db.Exec(ctx, removeSpeciesFromDeck, arg.DeckID, arg.SpeciesCode)
	return err
}

const updateDeck = `-- name: UpdateDeck :one
UPDATE decks SET name = $2, description = $3 WHERE id = $1
RETURNING id, name, description, owner_id, created_at
`

type UpdateDeckParams struct {
	ID          int64  `db:"id" json:"id"`
	Name        string `db:"name" json:"name"`
	Description string `db:"description" json:"description"`
}

func (q *Queries) UpdateDeck(ctx context.Context, arg UpdateDeckParams) (Deck, error) {
	row := q.db.QueryRow(ctx, updateDeck, arg.ID, arg.Name, arg.Description)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}
