// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addSpeciesToGroup = `-- name: AddSpeciesToGroup :exec
INSERT INTO group_species (group_id, species_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddSpeciesToGroupParams struct {
	GroupID   int64 `db:"group_id" json:"group_id"`
	SpeciesID int64 `db:"species_id" json:"species_id"`
}

func (q *Queries) AddSpeciesToGroup(ctx context.Context, arg AddSpeciesToGroupParams) error {
	_, err := q.db.Exec(ctx, addSpeciesToGroup, arg.GroupID, arg.SpeciesID)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, owner_id)
VALUES ($1, $2)
RETURNING id, name, description, is_preset, owner_id, created_at
`

type CreateGroupParams struct {
	Name    string      `db:"name" json:"name"`
	OwnerID pgtype.Int8 `db:"owner_id" json:"owner_id"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.Name, arg.OwnerID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPreset,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, description, is_preset, owner_id, created_at
FROM groups
WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id int64) (Group, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPreset,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const listGroupSpecies = `-- name: ListGroupSpecies :many
SELECT s.id, s.common_name, s.scientific_name, s.ebird_code
FROM species s
JOIN group_species gs ON gs.species_id = s.id
WHERE gs.group_id = $1
ORDER BY s.common_name
`

type ListGroupSpeciesRow struct {
	ID             int64  `db:"id" json:"id"`
	CommonName     string `db:"common_name" json:"common_name"`
	ScientificName string `db:"scientific_name" json:"scientific_name"`
	EbirdCode      string `db:"ebird_code" json:"ebird_code"`
}

func (q *Queries) ListGroupSpecies(ctx context.Context, groupID int64) ([]ListGroupSpeciesRow, error) {
	rows, err := q.db.Query(ctx, listGroupSpecies, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupSpeciesRow
	for rows.Next() {
		var i ListGroupSpeciesRow
		if err := rows.Scan(
			&i.ID,
			&i.CommonName,
			&i.ScientificName,
			&i.EbirdCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroups = `-- name: ListUserGroups :many
SELECT g.id, g.name, g.description, g.is_preset, g.owner_id, g.created_at,
    COUNT(CASE WHEN c.lane = 'audio' AND c.due <= NOW() THEN 1 END) AS audio_due,
    COUNT(CASE WHEN c.lane = 'image' AND c.due <= NOW() THEN 1 END) AS image_due
FROM groups g
LEFT JOIN group_species gs ON gs.group_id = g.id
LEFT JOIN cards c ON c.species_id = gs.species_id AND c.user_id = $1
WHERE g.owner_id = $1
GROUP BY g.id
ORDER BY g.name
`

type ListUserGroupsRow struct {
	ID          int64              `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description string             `db:"description" json:"description"`
	IsPreset    bool               `db:"is_preset" json:"is_preset"`
	OwnerID     pgtype.Int8        `db:"owner_id" json:"owner_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	AudioDue    int64              `db:"audio_due" json:"audio_due"`
	ImageDue    int64              `db:"image_due" json:"image_due"`
}

func (q *Queries) ListUserGroups(ctx context.Context, userID int64) ([]ListUserGroupsRow, error) {
	rows, err := q.db.Query(ctx, listUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserGroupsRow
	for rows.Next() {
		var i ListUserGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsPreset,
			&i.OwnerID,
			&i.CreatedAt,
			&i.AudioDue,
			&i.ImageDue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSpeciesFromGroup = `-- name: RemoveSpeciesFromGroup :exec
DELETE FROM group_species
WHERE group_id = $1 AND species_id = $2
`

type RemoveSpeciesFromGroupParams struct {
	GroupID   int64 `db:"group_id" json:"group_id"`
	SpeciesID int64 `db:"species_id" json:"species_id"`
}

func (q *Queries) RemoveSpeciesFromGroup(ctx context.Context, arg RemoveSpeciesFromGroupParams) error {
	_, err := q.db.Exec(ctx, removeSpeciesFromGroup, arg.GroupID, arg.SpeciesID)
	return err
}

const updateGroupName = `-- name: UpdateGroupName :one
UPDATE groups SET name = $2 WHERE id = $1
RETURNING id, name, description, is_preset, owner_id, created_at
`

type UpdateGroupNameParams struct {
	ID   int64  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}

func (q *Queries) UpdateGroupName(ctx context.Context, arg UpdateGroupNameParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroupName, arg.ID, arg.Name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPreset,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}
