// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingest.sql

package store

import (
	"context"
)

const deleteRecordingsBySpeciesCode = `-- name: DeleteRecordingsBySpeciesCode :exec
DELETE FROM species_recordings WHERE species_code = $1
`

func (q *Queries) DeleteRecordingsBySpeciesCode(ctx context.Context, speciesCode string) error {
	_, err := q.db.Exec(ctx, deleteRecordingsBySpeciesCode, speciesCode)
	return err
}

const deleteSpeciesByCode = `-- name: DeleteSpeciesByCode :exec
DELETE FROM species WHERE ebird_code = $1
`

func (q *Queries) DeleteSpeciesByCode(ctx context.Context, ebirdCode string) error {
	_, err := q.db.Exec(ctx, deleteSpeciesByCode, ebirdCode)
	return err
}

const deleteSpeciesImagesBySpeciesCode = `-- name: DeleteSpeciesImagesBySpeciesCode :exec
DELETE FROM species_images WHERE species_code = $1
`

func (q *Queries) DeleteSpeciesImagesBySpeciesCode(ctx context.Context, speciesCode string) error {
	_, err := q.db.Exec(ctx, deleteSpeciesImagesBySpeciesCode, speciesCode)
	return err
}

const listCompleteSpeciesEbirdCodes = `-- name: ListCompleteSpeciesEbirdCodes :many
SELECT s.ebird_code
FROM species s
WHERE EXISTS (SELECT 1 FROM species_recordings r WHERE r.species_code = s.ebird_code)
  AND EXISTS (SELECT 1 FROM species_images si WHERE si.species_code = s.ebird_code)
`

func (q *Queries) ListCompleteSpeciesEbirdCodes(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listCompleteSpeciesEbirdCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var ebird_code string
		if err := rows.Scan(&ebird_code); err != nil {
			return nil, err
		}
		items = append(items, ebird_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncompleteSpecies = `-- name: ListIncompleteSpecies :many
SELECT ebird_code FROM species
WHERE ebird_code NOT IN (SELECT DISTINCT species_code FROM species_recordings)
   OR ebird_code NOT IN (SELECT DISTINCT species_code FROM species_images)
`

func (q *Queries) ListIncompleteSpecies(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listIncompleteSpecies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var ebird_code string
		if err := rows.Scan(&ebird_code); err != nil {
			return nil, err
		}
		items = append(items, ebird_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRecording = `-- name: UpsertRecording :one
INSERT INTO species_recordings (xeno_canto_id, species_code, file_path, quality, type)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (xeno_canto_id) DO UPDATE
    SET file_path = EXCLUDED.file_path,
        quality   = EXCLUDED.quality,
        type      = EXCLUDED.type
RETURNING xeno_canto_id, species_code, file_path, quality, type, created_at, credit
`

type UpsertRecordingParams struct {
	XenoCantoID string `db:"xeno_canto_id" json:"xeno_canto_id"`
	SpeciesCode string `db:"species_code" json:"species_code"`
	FilePath    string `db:"file_path" json:"file_path"`
	Quality     string `db:"quality" json:"quality"`
	Type        string `db:"type" json:"type"`
}

func (q *Queries) UpsertRecording(ctx context.Context, arg UpsertRecordingParams) (SpeciesRecording, error) {
	row := q.db.QueryRow(ctx, upsertRecording,
		arg.XenoCantoID,
		arg.SpeciesCode,
		arg.FilePath,
		arg.Quality,
		arg.Type,
	)
	var i SpeciesRecording
	err := row.Scan(
		&i.XenoCantoID,
		&i.SpeciesCode,
		&i.FilePath,
		&i.Quality,
		&i.Type,
		&i.CreatedAt,
		&i.Credit,
	)
	return i, err
}

const upsertSpecies = `-- name: UpsertSpecies :one
INSERT INTO species (ebird_code, common_name, scientific_name)
VALUES ($1, $2, $3)
ON CONFLICT (ebird_code) DO UPDATE
    SET common_name     = EXCLUDED.common_name,
        scientific_name = EXCLUDED.scientific_name
RETURNING ebird_code, common_name, scientific_name, created_at
`

type UpsertSpeciesParams struct {
	EbirdCode      string `db:"ebird_code" json:"ebird_code"`
	CommonName     string `db:"common_name" json:"common_name"`
	ScientificName string `db:"scientific_name" json:"scientific_name"`
}

func (q *Queries) UpsertSpecies(ctx context.Context, arg UpsertSpeciesParams) (Species, error) {
	row := q.db.QueryRow(ctx, upsertSpecies, arg.EbirdCode, arg.CommonName, arg.ScientificName)
	var i Species
	err := row.Scan(
		&i.EbirdCode,
		&i.CommonName,
		&i.ScientificName,
		&i.CreatedAt,
	)
	return i, err
}

const upsertSpeciesImage = `-- name: UpsertSpeciesImage :one
INSERT INTO species_images (macaulay_id, species_code, file_path, credit)
VALUES ($1, $2, $3, $4)
ON CONFLICT (macaulay_id) DO UPDATE
    SET file_path = EXCLUDED.file_path,
        credit    = EXCLUDED.credit
RETURNING macaulay_id, species_code, file_path, credit, created_at
`

type UpsertSpeciesImageParams struct {
	MacaulayID  string `db:"macaulay_id" json:"macaulay_id"`
	SpeciesCode string `db:"species_code" json:"species_code"`
	FilePath    string `db:"file_path" json:"file_path"`
	Credit      string `db:"credit" json:"credit"`
}

func (q *Queries) UpsertSpeciesImage(ctx context.Context, arg UpsertSpeciesImageParams) (SpeciesImage, error) {
	row := q.db.QueryRow(ctx, upsertSpeciesImage,
		arg.MacaulayID,
		arg.SpeciesCode,
		arg.FilePath,
		arg.Credit,
	)
	var i SpeciesImage
	err := row.Scan(
		&i.MacaulayID,
		&i.SpeciesCode,
		&i.FilePath,
		&i.Credit,
		&i.CreatedAt,
	)
	return i, err
}
