// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingest.sql

package store

import (
	"context"
)

const upsertRecording = `-- name: UpsertRecording :one
INSERT INTO recordings (species_id, xeno_canto_id, file_path, quality, type)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (xeno_canto_id) DO UPDATE
    SET file_path = EXCLUDED.file_path,
        quality   = EXCLUDED.quality,
        type      = EXCLUDED.type
RETURNING id, species_id, xeno_canto_id, file_path, quality, created_at, type
`

type UpsertRecordingParams struct {
	SpeciesID   int64  `db:"species_id" json:"species_id"`
	XenoCantoID string `db:"xeno_canto_id" json:"xeno_canto_id"`
	FilePath    string `db:"file_path" json:"file_path"`
	Quality     string `db:"quality" json:"quality"`
	Type        string `db:"type" json:"type"`
}

func (q *Queries) UpsertRecording(ctx context.Context, arg UpsertRecordingParams) (Recording, error) {
	row := q.db.QueryRow(ctx, upsertRecording,
		arg.SpeciesID,
		arg.XenoCantoID,
		arg.FilePath,
		arg.Quality,
		arg.Type,
	)
	var i Recording
	err := row.Scan(
		&i.ID,
		&i.SpeciesID,
		&i.XenoCantoID,
		&i.FilePath,
		&i.Quality,
		&i.CreatedAt,
		&i.Type,
	)
	return i, err
}

const upsertSpecies = `-- name: UpsertSpecies :one
INSERT INTO species (common_name, scientific_name, ebird_code)
VALUES ($1, $2, $3)
ON CONFLICT (ebird_code) DO UPDATE
    SET common_name     = EXCLUDED.common_name,
        scientific_name = EXCLUDED.scientific_name
RETURNING id, common_name, scientific_name, ebird_code, created_at
`

type UpsertSpeciesParams struct {
	CommonName     string `db:"common_name" json:"common_name"`
	ScientificName string `db:"scientific_name" json:"scientific_name"`
	EbirdCode      string `db:"ebird_code" json:"ebird_code"`
}

func (q *Queries) UpsertSpecies(ctx context.Context, arg UpsertSpeciesParams) (Species, error) {
	row := q.db.QueryRow(ctx, upsertSpecies, arg.CommonName, arg.ScientificName, arg.EbirdCode)
	var i Species
	err := row.Scan(
		&i.ID,
		&i.CommonName,
		&i.ScientificName,
		&i.EbirdCode,
		&i.CreatedAt,
	)
	return i, err
}

const upsertSpeciesImage = `-- name: UpsertSpeciesImage :one
INSERT INTO species_images (species_id, macaulay_id, file_path, credit)
VALUES ($1, $2, $3, $4)
ON CONFLICT (macaulay_id) DO UPDATE
    SET file_path = EXCLUDED.file_path,
        credit    = EXCLUDED.credit
RETURNING id, species_id, macaulay_id, file_path, credit, created_at
`

type UpsertSpeciesImageParams struct {
	SpeciesID  int64  `db:"species_id" json:"species_id"`
	MacaulayID string `db:"macaulay_id" json:"macaulay_id"`
	FilePath   string `db:"file_path" json:"file_path"`
	Credit     string `db:"credit" json:"credit"`
}

func (q *Queries) UpsertSpeciesImage(ctx context.Context, arg UpsertSpeciesImageParams) (SpeciesImage, error) {
	row := q.db.QueryRow(ctx, upsertSpeciesImage,
		arg.SpeciesID,
		arg.MacaulayID,
		arg.FilePath,
		arg.Credit,
	)
	var i SpeciesImage
	err := row.Scan(
		&i.ID,
		&i.SpeciesID,
		&i.MacaulayID,
		&i.FilePath,
		&i.Credit,
		&i.CreatedAt,
	)
	return i, err
}
