// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Card struct {
	ID          int64              `db:"id" json:"id"`
	UserID      int64              `db:"user_id" json:"user_id"`
	RecordingID int64              `db:"recording_id" json:"recording_id"`
	Stability   float64            `db:"stability" json:"stability"`
	Difficulty  float64            `db:"difficulty" json:"difficulty"`
	Due         pgtype.Timestamptz `db:"due" json:"due"`
	LastReview  pgtype.Timestamptz `db:"last_review" json:"last_review"`
	Reps        int32              `db:"reps" json:"reps"`
	Lapses      int32              `db:"lapses" json:"lapses"`
	State       int16              `db:"state" json:"state"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Group struct {
	ID          int64              `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description string             `db:"description" json:"description"`
	IsPreset    bool               `db:"is_preset" json:"is_preset"`
	OwnerID     pgtype.Int8        `db:"owner_id" json:"owner_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type GroupSpecy struct {
	GroupID   int64 `db:"group_id" json:"group_id"`
	SpeciesID int64 `db:"species_id" json:"species_id"`
}

type Species struct {
	ID             int64              `db:"id" json:"id"`
	CommonName     string             `db:"common_name" json:"common_name"`
	ScientificName string             `db:"scientific_name" json:"scientific_name"`
	EbirdCode      string             `db:"ebird_code" json:"ebird_code"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type SpeciesImage struct {
	ID         int64              `db:"id" json:"id"`
	SpeciesID  int64              `db:"species_id" json:"species_id"`
	MacaulayID string             `db:"macaulay_id" json:"macaulay_id"`
	FilePath   string             `db:"file_path" json:"file_path"`
	Credit     string             `db:"credit" json:"credit"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type SpeciesRecording struct {
	ID          int64              `db:"id" json:"id"`
	SpeciesID   int64              `db:"species_id" json:"species_id"`
	XenoCantoID string             `db:"xeno_canto_id" json:"xeno_canto_id"`
	FilePath    string             `db:"file_path" json:"file_path"`
	Quality     string             `db:"quality" json:"quality"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Type        string             `db:"type" json:"type"`
}

type User struct {
	ID        int64              `db:"id" json:"id"`
	GoogleID  string             `db:"google_id" json:"google_id"`
	Email     string             `db:"email" json:"email"`
	Name      string             `db:"name" json:"name"`
	Picture   string             `db:"picture" json:"picture"`
	IsAdmin   bool               `db:"is_admin" json:"is_admin"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
