// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Card struct {
	ID          int64              `db:"id" json:"id"`
	UserID      int64              `db:"user_id" json:"user_id"`
	SpeciesCode string             `db:"species_code" json:"species_code"`
	Lane        string             `db:"lane" json:"lane"`
	Stability   float64            `db:"stability" json:"stability"`
	Difficulty  float64            `db:"difficulty" json:"difficulty"`
	Due         pgtype.Timestamptz `db:"due" json:"due"`
	LastReview  pgtype.Timestamptz `db:"last_review" json:"last_review"`
	Reps        int32              `db:"reps" json:"reps"`
	Lapses      int32              `db:"lapses" json:"lapses"`
	State       int16              `db:"state" json:"state"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Deck struct {
	ID          int64              `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description string             `db:"description" json:"description"`
	OwnerID     pgtype.Int8        `db:"owner_id" json:"owner_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type DeckSpecy struct {
	DeckID      int64  `db:"deck_id" json:"deck_id"`
	SpeciesCode string `db:"species_code" json:"species_code"`
}

type ReviewLog struct {
	ID                 int64              `db:"id" json:"id"`
	UserID             int64              `db:"user_id" json:"user_id"`
	SpeciesCode        string             `db:"species_code" json:"species_code"`
	Lane               string             `db:"lane" json:"lane"`
	Rating             int16              `db:"rating" json:"rating"`
	GuessedSpeciesCode pgtype.Text        `db:"guessed_species_code" json:"guessed_species_code"`
	MediaID            pgtype.Text        `db:"media_id" json:"media_id"`
	ReviewedAt         pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
}

type Species struct {
	EbirdCode      string             `db:"ebird_code" json:"ebird_code"`
	CommonName     string             `db:"common_name" json:"common_name"`
	ScientificName string             `db:"scientific_name" json:"scientific_name"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Family         pgtype.Text        `db:"family" json:"family"`
}

type SpeciesImage struct {
	MacaulayID  string             `db:"macaulay_id" json:"macaulay_id"`
	SpeciesCode string             `db:"species_code" json:"species_code"`
	FilePath    string             `db:"file_path" json:"file_path"`
	Credit      string             `db:"credit" json:"credit"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Locked      bool               `db:"locked" json:"locked"`
}

type SpeciesRecording struct {
	XenoCantoID string             `db:"xeno_canto_id" json:"xeno_canto_id"`
	SpeciesCode string             `db:"species_code" json:"species_code"`
	FilePath    string             `db:"file_path" json:"file_path"`
	Quality     string             `db:"quality" json:"quality"`
	Type        string             `db:"type" json:"type"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Credit      string             `db:"credit" json:"credit"`
	Locked      bool               `db:"locked" json:"locked"`
}

type User struct {
	ID        int64              `db:"id" json:"id"`
	GoogleID  string             `db:"google_id" json:"google_id"`
	Email     string             `db:"email" json:"email"`
	Name      string             `db:"name" json:"name"`
	Picture   string             `db:"picture" json:"picture"`
	IsAdmin   bool               `db:"is_admin" json:"is_admin"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UserSpeciesPreference struct {
	UserID       int64              `db:"user_id" json:"user_id"`
	SpeciesCode  string             `db:"species_code" json:"species_code"`
	AudioEnabled bool               `db:"audio_enabled" json:"audio_enabled"`
	ImageEnabled bool               `db:"image_enabled" json:"image_enabled"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
