// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preferences.sql

package store

import (
	"context"
)

const getPreferences = `-- name: GetPreferences :one
SELECT user_id, species_id, audio_enabled, image_enabled, created_at
FROM user_species_preferences
WHERE user_id = $1 AND species_id = $2
`

type GetPreferencesParams struct {
	UserID    int64 `db:"user_id" json:"user_id"`
	SpeciesID int64 `db:"species_id" json:"species_id"`
}

func (q *Queries) GetPreferences(ctx context.Context, arg GetPreferencesParams) (UserSpeciesPreference, error) {
	row := q.db.QueryRow(ctx, getPreferences, arg.UserID, arg.SpeciesID)
	var i UserSpeciesPreference
	err := row.Scan(
		&i.UserID,
		&i.SpeciesID,
		&i.AudioEnabled,
		&i.ImageEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const upsertPreferences = `-- name: UpsertPreferences :one
INSERT INTO user_species_preferences (user_id, species_id, audio_enabled, image_enabled)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, species_id) DO UPDATE
SET audio_enabled = EXCLUDED.audio_enabled,
    image_enabled = EXCLUDED.image_enabled
RETURNING user_id, species_id, audio_enabled, image_enabled, created_at
`

type UpsertPreferencesParams struct {
	UserID       int64 `db:"user_id" json:"user_id"`
	SpeciesID    int64 `db:"species_id" json:"species_id"`
	AudioEnabled bool  `db:"audio_enabled" json:"audio_enabled"`
	ImageEnabled bool  `db:"image_enabled" json:"image_enabled"`
}

func (q *Queries) UpsertPreferences(ctx context.Context, arg UpsertPreferencesParams) (UserSpeciesPreference, error) {
	row := q.db.QueryRow(ctx, upsertPreferences,
		arg.UserID,
		arg.SpeciesID,
		arg.AudioEnabled,
		arg.ImageEnabled,
	)
	var i UserSpeciesPreference
	err := row.Scan(
		&i.UserID,
		&i.SpeciesID,
		&i.AudioEnabled,
		&i.ImageEnabled,
		&i.CreatedAt,
	)
	return i, err
}
