// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddSpeciesToDeck(ctx context.Context, arg AddSpeciesToDeckParams) error
	BulkAddSpeciesToDeck(ctx context.Context, arg BulkAddSpeciesToDeckParams) (int64, error)
	BulkUpsertCards(ctx context.Context, arg BulkUpsertCardsParams) error
	CloneDeckSpecies(ctx context.Context, arg CloneDeckSpeciesParams) error
	CountReviewsSince(ctx context.Context, arg CountReviewsSinceParams) (int64, error)
	CreateDeck(ctx context.Context, arg CreateDeckParams) (Deck, error)
	CreatePresetDeck(ctx context.Context, arg CreatePresetDeckParams) (Deck, error)
	CreateReviewLog(ctx context.Context, arg CreateReviewLogParams) (ReviewLog, error)
	DeleteAllCardsForUser(ctx context.Context, userID int64) (int64, error)
	DeleteAllReviewsForUser(ctx context.Context, userID int64) (int64, error)
	DeleteCard(ctx context.Context, arg DeleteCardParams) error
	DeleteDeck(ctx context.Context, id int64) error
	DeleteImage(ctx context.Context, macaulayID string) error
	DeleteRecording(ctx context.Context, xenoCantoID string) error
	DeleteRecordingsBySpeciesCode(ctx context.Context, speciesCode string) error
	DeleteSpeciesByCode(ctx context.Context, ebirdCode string) error
	DeleteSpeciesImagesBySpeciesCode(ctx context.Context, speciesCode string) error
	GetCard(ctx context.Context, arg GetCardParams) (Card, error)
	// Stats: per-card bucket counts. Buckets per the stats spec: not_seen = never
	// reviewed; known = FSRS Review state; relearning = lapsed; else learning.
	// Preference-disabled lanes are excluded to match GetNextDueCard: a lane the
	// user toggled off is never served, so its cards stay reps = 0 forever and
	// would otherwise haunt the progress bar as permanent, unclearable not_seen.
	GetCardStateCounts(ctx context.Context, arg GetCardStateCountsParams) ([]GetCardStateCountsRow, error)
	// Totals mirror GetCardStateCounts' lane-preference filter so disabled lanes
	// don't inflate card/species/review counts.
	GetCardTotals(ctx context.Context, arg GetCardTotalsParams) (GetCardTotalsRow, error)
	// Stats: actual misidentifications only (skips have NULL guesses).
	GetConfusionPairs(ctx context.Context, arg GetConfusionPairsParams) ([]GetConfusionPairsRow, error)
	GetDeck(ctx context.Context, id int64) (Deck, error)
	GetDeckPracticeCards(ctx context.Context, deckID int64) ([]GetDeckPracticeCardsRow, error)
	GetDeckWithDue(ctx context.Context, arg GetDeckWithDueParams) (GetDeckWithDueRow, error)
	GetDeckWithOwner(ctx context.Context, id int64) (GetDeckWithOwnerRow, error)
	GetDecksForSpecies(ctx context.Context, arg GetDecksForSpeciesParams) ([]int64, error)
	// Seeder: every card of the user's due at the given instant, all decks,
	// both lanes (the quiz path's GetNextDueCard is deck- and lane-scoped).
	// Mirrors the quiz's media filter: never simulate a review the real app
	// could not serve.
	GetDueCardsForUser(ctx context.Context, arg GetDueCardsForUserParams) ([]Card, error)
	// Stats: accuracy by eBird family; species without a backfilled family are omitted.
	GetFamilyAccuracy(ctx context.Context, arg GetFamilyAccuracyParams) ([]GetFamilyAccuracyRow, error)
	// Stats: specific media the user keeps missing (>=3 looks). media_url resolves
	// opportunistically -- deleted media yields ''.
	GetHardMedia(ctx context.Context, arg GetHardMediaParams) ([]GetHardMediaRow, error)
	GetImageByID(ctx context.Context, macaulayID string) (GetImageByIDRow, error)
	// Stats: known cards with FSRS fields for retrievability math in Go.
	// "Known" here (state = 2) is intentionally equivalent to GetCardStateCounts'
	// known bucket: FSRS cannot produce state 2 with reps = 0, so the two
	// predicates cannot diverge. Keep them in sync if either changes -- including
	// the lane-preference filter below, so a known-then-disabled card doesn't show
	// in Fading/Remember while vanishing from the progress bar.
	GetKnownCards(ctx context.Context, arg GetKnownCardsParams) ([]GetKnownCardsRow, error)
	// Stats: species known in exactly one lane, biggest stability gap first.
	// Both lanes must be enabled for a gap to be actionable -- if the weak lane is
	// disabled, the user opted out of practicing it, so it's not a gap to surface.
	GetLaneGaps(ctx context.Context, userID int64) ([]GetLaneGapsRow, error)
	GetNextDueAt(ctx context.Context, userID int64) (pgtype.Timestamptz, error)
	// Bucket due-time by the minute, then shuffle within the bucket. A fresh deck
	// seeds every card with an identical `due`; a plain `ORDER BY c.due` left the
	// tiebreak to the scan order, so the quiz replayed the same species sequence
	// every session. Minute granularity keeps FSRS's 1-10min learning steps in
	// order while randomising the (always-tied) fresh cards.
	GetNextDueCard(ctx context.Context, arg GetNextDueCardParams) (GetNextDueCardRow, error)
	GetPreferences(ctx context.Context, arg GetPreferencesParams) (UserSpeciesPreference, error)
	// GetRandomMediaForSpecies picks a random quiz-quality recording and a random
	// image in one round trip (same LATERAL pattern as GetDeckPracticeCards).
	// Missing media comes back as empty strings.
	GetRandomMediaForSpecies(ctx context.Context, dollar_1 string) (GetRandomMediaForSpeciesRow, error)
	GetRecordingByID(ctx context.Context, xenoCantoID string) (GetRecordingByIDRow, error)
	GetReviewAccuracy(ctx context.Context, arg GetReviewAccuracyParams) (GetReviewAccuracyRow, error)
	GetSpeciesByCode(ctx context.Context, ebirdCode string) (GetSpeciesByCodeRow, error)
	GetSpeciesImages(ctx context.Context, speciesCode string) ([]GetSpeciesImagesRow, error)
	GetSpeciesRecordings(ctx context.Context, speciesCode string) ([]GetSpeciesRecordingsRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Columns are enumerated (no SELECT */RETURNING *) so that adding a column to
	// users is an explicit decision per query, not a silent change to API output.
	GetUserByGoogleID(ctx context.Context, googleID string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	// Seeder: distinct species (with family) across the user's decks, for
	// picking plausible confusable wrong answers.
	GetUserDeckSpecies(ctx context.Context, userID int64) ([]GetUserDeckSpeciesRow, error)
	// GetUsers feeds the admin users API: google_id is deliberately excluded so
	// third-party identifiers never reach the client.
	GetUsers(ctx context.Context) ([]GetUsersRow, error)
	ListAllSpecies(ctx context.Context) ([]ListAllSpeciesRow, error)
	ListAllUserDecks(ctx context.Context) ([]ListAllUserDecksRow, error)
	ListCompleteSpeciesEbirdCodes(ctx context.Context) ([]string, error)
	ListDeckSpeciesSimple(ctx context.Context, deckID int64) ([]ListDeckSpeciesSimpleRow, error)
	ListDeckSpeciesWithPrefs(ctx context.Context, arg ListDeckSpeciesWithPrefsParams) ([]ListDeckSpeciesWithPrefsRow, error)
	ListIncompleteSpecies(ctx context.Context) ([]string, error)
	ListPresetDecks(ctx context.Context) ([]ListPresetDecksRow, error)
	ListSpecies(ctx context.Context, arg ListSpeciesParams) ([]ListSpeciesRow, error)
	ListSpeciesCodes(ctx context.Context) ([]string, error)
	// Species with any locked media are protected from ingest cleanup: deleting
	// the species row would cascade onto locked rows, so cleanup must skip them.
	ListSpeciesCodesWithLockedMedia(ctx context.Context) ([]string, error)
	ListUserDecks(ctx context.Context, userID int64) ([]ListUserDecksRow, error)
	RemoveSpeciesFromDeck(ctx context.Context, arg RemoveSpeciesFromDeckParams) error
	SearchSpecies(ctx context.Context, dollar_1 pgtype.Text) ([]SearchSpeciesRow, error)
	// Re-seed blank cards for every species in the user's decks (both lanes,
	// minus preference-disabled ones). Used by reset: nothing else re-creates
	// cards for already-added species, so without this a reset leaves existing
	// decks permanently card-less.
	SeedCardsForUserDecks(ctx context.Context, userID int64) (int64, error)
	SetImageLocked(ctx context.Context, arg SetImageLockedParams) error
	SetRecordingLocked(ctx context.Context, arg SetRecordingLockedParams) error
	SetUserIsAdmin(ctx context.Context, arg SetUserIsAdminParams) error
	UpdateCardSchedule(ctx context.Context, arg UpdateCardScheduleParams) (Card, error)
	UpdateDeck(ctx context.Context, arg UpdateDeckParams) (Deck, error)
	UpsertCard(ctx context.Context, arg UpsertCardParams) error
	UpsertCardsForDeck(ctx context.Context, arg UpsertCardsForDeckParams) error
	UpsertPreferences(ctx context.Context, arg UpsertPreferencesParams) (UserSpeciesPreference, error)
	// "locked" protects media from REMOVAL only (see the cleanup path and the
	// NOT locked delete guards below); ingest may still add new media to a locked
	// bird and refresh same-source fields on existing rows.
	UpsertRecording(ctx context.Context, arg UpsertRecordingParams) (SpeciesRecording, error)
	UpsertSpecies(ctx context.Context, arg UpsertSpeciesParams) (Species, error)
	UpsertSpeciesImage(ctx context.Context, arg UpsertSpeciesImageParams) (SpeciesImage, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
