// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	GetDueCards(ctx context.Context, arg GetDueCardsParams) ([]GetDueCardsRow, error)
	GetUserByGoogleID(ctx context.Context, googleID string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	UpdateCardSchedule(ctx context.Context, arg UpdateCardScheduleParams) (Card, error)
	UpsertCard(ctx context.Context, arg UpsertCardParams) (Card, error)
	UpsertRecording(ctx context.Context, arg UpsertRecordingParams) (Recording, error)
	UpsertSpecies(ctx context.Context, arg UpsertSpeciesParams) (Species, error)
	UpsertSpeciesImage(ctx context.Context, arg UpsertSpeciesImageParams) (SpeciesImage, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
