// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review_log.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReviewsSince = `-- name: CountReviewsSince :one
SELECT COUNT(*)
FROM review_log
WHERE user_id = $1
  AND reviewed_at > $2
  AND lane = COALESCE($3, lane)
`

type CountReviewsSinceParams struct {
	UserID     int64              `db:"user_id" json:"user_id"`
	ReviewedAt pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	Lane       pgtype.Text        `db:"lane" json:"lane"`
}

func (q *Queries) CountReviewsSince(ctx context.Context, arg CountReviewsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReviewsSince, arg.UserID, arg.ReviewedAt, arg.Lane)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReviewLog = `-- name: CreateReviewLog :one
INSERT INTO review_log (user_id, species_code, lane, rating, guessed_species_code, media_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, species_code, lane, rating, guessed_species_code, media_id, reviewed_at
`

type CreateReviewLogParams struct {
	UserID             int64       `db:"user_id" json:"user_id"`
	SpeciesCode        string      `db:"species_code" json:"species_code"`
	Lane               string      `db:"lane" json:"lane"`
	Rating             int16       `db:"rating" json:"rating"`
	GuessedSpeciesCode pgtype.Text `db:"guessed_species_code" json:"guessed_species_code"`
	MediaID            pgtype.Text `db:"media_id" json:"media_id"`
}

func (q *Queries) CreateReviewLog(ctx context.Context, arg CreateReviewLogParams) (ReviewLog, error) {
	row := q.db.QueryRow(ctx, createReviewLog,
		arg.UserID,
		arg.SpeciesCode,
		arg.Lane,
		arg.Rating,
		arg.GuessedSpeciesCode,
		arg.MediaID,
	)
	var i ReviewLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SpeciesCode,
		&i.Lane,
		&i.Rating,
		&i.GuessedSpeciesCode,
		&i.MediaID,
		&i.ReviewedAt,
	)
	return i, err
}

const deleteAllReviewsForUser = `-- name: DeleteAllReviewsForUser :execrows
DELETE FROM review_log
WHERE user_id = $1
`

func (q *Queries) DeleteAllReviewsForUser(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAllReviewsForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConfusionPairs = `-- name: GetConfusionPairs :many
SELECT rl.species_code,
       a.common_name     AS actual_common_name,
       a.scientific_name AS actual_scientific_name,
       rl.guessed_species_code::text AS guessed_species_code,
       g.common_name     AS guessed_common_name,
       g.scientific_name AS guessed_scientific_name,
       COUNT(*)          AS count
FROM review_log rl
JOIN species a ON a.ebird_code = rl.species_code
JOIN species g ON g.ebird_code = rl.guessed_species_code
WHERE rl.user_id = $1
  AND rl.guessed_species_code IS NOT NULL
  AND rl.guessed_species_code <> rl.species_code
  AND rl.lane = COALESCE($2, rl.lane)
GROUP BY rl.species_code, a.common_name, a.scientific_name,
         rl.guessed_species_code, g.common_name, g.scientific_name
ORDER BY count DESC, rl.species_code
LIMIT 10
`

type GetConfusionPairsParams struct {
	UserID int64       `db:"user_id" json:"user_id"`
	Lane   pgtype.Text `db:"lane" json:"lane"`
}

type GetConfusionPairsRow struct {
	SpeciesCode           string `db:"species_code" json:"species_code"`
	ActualCommonName      string `db:"actual_common_name" json:"actual_common_name"`
	ActualScientificName  string `db:"actual_scientific_name" json:"actual_scientific_name"`
	GuessedSpeciesCode    string `db:"guessed_species_code" json:"guessed_species_code"`
	GuessedCommonName     string `db:"guessed_common_name" json:"guessed_common_name"`
	GuessedScientificName string `db:"guessed_scientific_name" json:"guessed_scientific_name"`
	Count                 int64  `db:"count" json:"count"`
}

// Stats: actual misidentifications only (skips have NULL guesses).
func (q *Queries) GetConfusionPairs(ctx context.Context, arg GetConfusionPairsParams) ([]GetConfusionPairsRow, error) {
	rows, err := q.db.Query(ctx, getConfusionPairs, arg.UserID, arg.Lane)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConfusionPairsRow
	for rows.Next() {
		var i GetConfusionPairsRow
		if err := rows.Scan(
			&i.SpeciesCode,
			&i.ActualCommonName,
			&i.ActualScientificName,
			&i.GuessedSpeciesCode,
			&i.GuessedCommonName,
			&i.GuessedScientificName,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFamilyAccuracy = `-- name: GetFamilyAccuracy :many
SELECT s.family::text AS family,
       COUNT(*) AS attempts,
       COUNT(*) FILTER (WHERE rl.rating = 3) AS correct
FROM review_log rl
JOIN species s ON s.ebird_code = rl.species_code
WHERE rl.user_id = $1
  AND s.family IS NOT NULL
  AND rl.lane = COALESCE($2, rl.lane)
GROUP BY s.family
ORDER BY (COUNT(*) FILTER (WHERE rl.rating = 3))::float / COUNT(*) ASC, attempts DESC
LIMIT 10
`

type GetFamilyAccuracyParams struct {
	UserID int64       `db:"user_id" json:"user_id"`
	Lane   pgtype.Text `db:"lane" json:"lane"`
}

type GetFamilyAccuracyRow struct {
	Family   string `db:"family" json:"family"`
	Attempts int64  `db:"attempts" json:"attempts"`
	Correct  int64  `db:"correct" json:"correct"`
}

// Stats: accuracy by eBird family; species without a backfilled family are omitted.
func (q *Queries) GetFamilyAccuracy(ctx context.Context, arg GetFamilyAccuracyParams) ([]GetFamilyAccuracyRow, error) {
	rows, err := q.db.Query(ctx, getFamilyAccuracy, arg.UserID, arg.Lane)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFamilyAccuracyRow
	for rows.Next() {
		var i GetFamilyAccuracyRow
		if err := rows.Scan(&i.Family, &i.Attempts, &i.Correct); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHardMedia = `-- name: GetHardMedia :many
SELECT rl.media_id::text AS media_id,
       rl.lane,
       rl.species_code,
       s.common_name,
       s.scientific_name,
       COALESCE(MAX(sr.file_path), MAX(si.file_path), '')::text AS media_url,
       COUNT(*) AS attempts,
       COUNT(*) FILTER (WHERE rl.rating = 3) AS correct
FROM review_log rl
JOIN species s ON s.ebird_code = rl.species_code
LEFT JOIN species_recordings sr ON rl.lane = 'audio' AND sr.xeno_canto_id = rl.media_id
LEFT JOIN species_images si    ON rl.lane = 'image' AND si.macaulay_id  = rl.media_id
WHERE rl.user_id = $1
  AND rl.media_id IS NOT NULL
  AND rl.lane = COALESCE($2, rl.lane)
GROUP BY rl.media_id, rl.lane, rl.species_code, s.common_name, s.scientific_name
HAVING COUNT(*) >= 3
ORDER BY (COUNT(*) FILTER (WHERE rl.rating = 3))::float / COUNT(*) ASC, attempts DESC
LIMIT 10
`

type GetHardMediaParams struct {
	UserID int64       `db:"user_id" json:"user_id"`
	Lane   pgtype.Text `db:"lane" json:"lane"`
}

type GetHardMediaRow struct {
	MediaID        string `db:"media_id" json:"media_id"`
	Lane           string `db:"lane" json:"lane"`
	SpeciesCode    string `db:"species_code" json:"species_code"`
	CommonName     string `db:"common_name" json:"common_name"`
	ScientificName string `db:"scientific_name" json:"scientific_name"`
	MediaUrl       string `db:"media_url" json:"media_url"`
	Attempts       int64  `db:"attempts" json:"attempts"`
	Correct        int64  `db:"correct" json:"correct"`
}

// Stats: specific media the user keeps missing (>=3 looks). media_url resolves
// opportunistically -- deleted media yields ”.
func (q *Queries) GetHardMedia(ctx context.Context, arg GetHardMediaParams) ([]GetHardMediaRow, error) {
	rows, err := q.db.Query(ctx, getHardMedia, arg.UserID, arg.Lane)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHardMediaRow
	for rows.Next() {
		var i GetHardMediaRow
		if err := rows.Scan(
			&i.MediaID,
			&i.Lane,
			&i.SpeciesCode,
			&i.CommonName,
			&i.ScientificName,
			&i.MediaUrl,
			&i.Attempts,
			&i.Correct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewAccuracy = `-- name: GetReviewAccuracy :one
SELECT COUNT(*) AS attempts,
       COUNT(*) FILTER (WHERE rating = 3) AS correct
FROM review_log
WHERE user_id = $1
  AND lane = COALESCE($2, lane)
`

type GetReviewAccuracyParams struct {
	UserID int64       `db:"user_id" json:"user_id"`
	Lane   pgtype.Text `db:"lane" json:"lane"`
}

type GetReviewAccuracyRow struct {
	Attempts int64 `db:"attempts" json:"attempts"`
	Correct  int64 `db:"correct" json:"correct"`
}

func (q *Queries) GetReviewAccuracy(ctx context.Context, arg GetReviewAccuracyParams) (GetReviewAccuracyRow, error) {
	row := q.db.QueryRow(ctx, getReviewAccuracy, arg.UserID, arg.Lane)
	var i GetReviewAccuracyRow
	err := row.Scan(&i.Attempts, &i.Correct)
	return i, err
}
