// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review_log.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReviewLog = `-- name: CreateReviewLog :one
INSERT INTO review_log (user_id, species_code, lane, rating, guessed_species_code, media_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, species_code, lane, rating, guessed_species_code, media_id, reviewed_at
`

type CreateReviewLogParams struct {
	UserID             int64       `db:"user_id" json:"user_id"`
	SpeciesCode        string      `db:"species_code" json:"species_code"`
	Lane               string      `db:"lane" json:"lane"`
	Rating             int16       `db:"rating" json:"rating"`
	GuessedSpeciesCode pgtype.Text `db:"guessed_species_code" json:"guessed_species_code"`
	MediaID            pgtype.Text `db:"media_id" json:"media_id"`
}

func (q *Queries) CreateReviewLog(ctx context.Context, arg CreateReviewLogParams) (ReviewLog, error) {
	row := q.db.QueryRow(ctx, createReviewLog,
		arg.UserID,
		arg.SpeciesCode,
		arg.Lane,
		arg.Rating,
		arg.GuessedSpeciesCode,
		arg.MediaID,
	)
	var i ReviewLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SpeciesCode,
		&i.Lane,
		&i.Rating,
		&i.GuessedSpeciesCode,
		&i.MediaID,
		&i.ReviewedAt,
	)
	return i, err
}
