// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: species.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const searchSpecies = `-- name: SearchSpecies :many
SELECT ebird_code, common_name, scientific_name
FROM species
WHERE common_name ILIKE '%' || $1 || '%'
   OR scientific_name ILIKE '%' || $1 || '%'
ORDER BY common_name
LIMIT 20
`

type SearchSpeciesRow struct {
	EbirdCode      string `db:"ebird_code" json:"ebird_code"`
	CommonName     string `db:"common_name" json:"common_name"`
	ScientificName string `db:"scientific_name" json:"scientific_name"`
}

func (q *Queries) SearchSpecies(ctx context.Context, dollar_1 pgtype.Text) ([]SearchSpeciesRow, error) {
	rows, err := q.db.Query(ctx, searchSpecies, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSpeciesRow
	for rows.Next() {
		var i SearchSpeciesRow
		if err := rows.Scan(&i.EbirdCode, &i.CommonName, &i.ScientificName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
