// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transcode.sql

package store

import (
	"context"
)

const listRecordingsForTranscode = `-- name: ListRecordingsForTranscode :many

SELECT xeno_canto_id, species_code, file_path, peaks
FROM species_recordings
ORDER BY species_code, xeno_canto_id
`

type ListRecordingsForTranscodeRow struct {
	XenoCantoID string  `db:"xeno_canto_id" json:"xeno_canto_id"`
	SpeciesCode string  `db:"species_code" json:"species_code"`
	FilePath    string  `db:"file_path" json:"file_path"`
	Peaks       []int16 `db:"peaks" json:"peaks"`
}

// Queries for cmd/transcode. Deliberately narrow: the job reads recordings and
// writes peaks, nothing else. It must never reach ingest's cleanup queries,
// which delete species rows DB-wide and cascade to cards and review_log.
func (q *Queries) ListRecordingsForTranscode(ctx context.Context) ([]ListRecordingsForTranscodeRow, error) {
	rows, err := q.db.Query(ctx, listRecordingsForTranscode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecordingsForTranscodeRow
	for rows.Next() {
		var i ListRecordingsForTranscodeRow
		if err := rows.Scan(
			&i.XenoCantoID,
			&i.SpeciesCode,
			&i.FilePath,
			&i.Peaks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRecordingPeaks = `-- name: SetRecordingPeaks :exec
UPDATE species_recordings SET peaks = $2 WHERE xeno_canto_id = $1
`

type SetRecordingPeaksParams struct {
	XenoCantoID string  `db:"xeno_canto_id" json:"xeno_canto_id"`
	Peaks       []int16 `db:"peaks" json:"peaks"`
}

func (q *Queries) SetRecordingPeaks(ctx context.Context, arg SetRecordingPeaksParams) error {
	_, err := q.db.Exec(ctx, setRecordingPeaks, arg.XenoCantoID, arg.Peaks)
	return err
}
