// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, google_id, email, name, picture, is_admin, created_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one

SELECT id, google_id, email, name, picture, is_admin, created_at
FROM users WHERE google_id = $1
`

// Columns are enumerated (no SELECT */RETURNING *) so that adding a column to
// users is an explicit decision per query, not a silent change to API output.
func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, google_id, email, name, picture, is_admin, created_at
FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, email, name, picture, is_admin, created_at FROM users
`

type GetUsersRow struct {
	ID        int64              `db:"id" json:"id"`
	Email     string             `db:"email" json:"email"`
	Name      string             `db:"name" json:"name"`
	Picture   string             `db:"picture" json:"picture"`
	IsAdmin   bool               `db:"is_admin" json:"is_admin"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// GetUsers feeds the admin users API: google_id is deliberately excluded so
// third-party identifiers never reach the client.
func (q *Queries) GetUsers(ctx context.Context) ([]GetUsersRow, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersRow
	for rows.Next() {
		var i GetUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Picture,
			&i.IsAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserIsAdmin = `-- name: SetUserIsAdmin :exec
UPDATE users SET is_admin = $2 WHERE id = $1
`

type SetUserIsAdminParams struct {
	ID      int64 `db:"id" json:"id"`
	IsAdmin bool  `db:"is_admin" json:"is_admin"`
}

func (q *Queries) SetUserIsAdmin(ctx context.Context, arg SetUserIsAdminParams) error {
	_, err := q.db.Exec(ctx, setUserIsAdmin, arg.ID, arg.IsAdmin)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (google_id, email, name, picture)
VALUES ($1, $2, $3, $4)
ON CONFLICT (google_id) DO UPDATE
    SET email   = EXCLUDED.email,
        name    = EXCLUDED.name,
        picture = EXCLUDED.picture
RETURNING id, google_id, email, name, picture, is_admin, created_at
`

type UpsertUserParams struct {
	GoogleID string `db:"google_id" json:"google_id"`
	Email    string `db:"email" json:"email"`
	Name     string `db:"name" json:"name"`
	Picture  string `db:"picture" json:"picture"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.GoogleID,
		arg.Email,
		arg.Name,
		arg.Picture,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}
