DROP TABLE IF EXISTS user_species_preferences CASCADE;
DROP TABLE IF EXISTS cards CASCADE;
DROP TABLE IF EXISTS group_species CASCADE;
DROP TABLE IF EXISTS groups CASCADE;
DROP TABLE IF EXISTS species_images CASCADE;
DROP TABLE IF EXISTS species_recordings CASCADE;
DROP TABLE IF EXISTS species CASCADE;
DROP TABLE IF EXISTS users CASCADE;
