DROP TABLE IF EXISTS cards;
DROP TABLE IF EXISTS group_species;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS species_images;
DROP TABLE IF EXISTS recordings;
DROP TABLE IF EXISTS species;
DROP TABLE IF EXISTS users;
